### ISSUE TITLE
Adapt luci-app-batman-adv for work with Alfred

### ISSUE THREAD

**Issue by p4u** [libremesh/lime-packages#1]
luci-app-batman-adv topology graph does not work with last batman-adv. The "batcl vm" option has been removed from batman-adv and transfered to the userspace application "Alfred". So the luci-app-batman-adv should have alfred as dependency and the Lua code should be adapted.

**Comment by ilario** [comment]
This was closed by error by GitHub due to commit comment by Pau in 6d129a4

**Comment by ilario** [comment]
I'm working on this, changing from `batctl vd output_format` to `batadv-vis -f output_format` and from `batctl vm new_mode` to `alfred --modeswitch new_mode`. Both in luci-app-batman-adv [controller](/libremesh/lime-packages/blob/develop/packages/luci-app-batman-adv/files/usr/lib/lua/luci/controller/batman.lua) and [viewer](/libremesh/lime-packages/blob/develop/packages/luci-app-batman-adv/files/usr/lib/lua/luci/view/batman.htm).
What I miss is a way to get the current alfred mode (master or slave), which was possible to get with `batctl vm`. Does anyone have suggestions on this?

**Comment by p4u** [comment]
>  uci get alfred.alfred.mode

**Comment by ilario** [comment]
Thanks @p4u, that's what I was missing :)
This issue was finally addressed by @altergui in #225, just the switch for `master` to `slave` mode is gone. I can reintroduce that if you think is needed, otherwise we can close.
