### ISSUE TITLE
Autoconfig SSID

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#100]
Instead of setting up the name of the network on firmware-build time, allow the firmware to decide which network will be by looking at the networks that are close to him.
Give the user an interface in which the user can choose to join a network that is already deployed, or to create a new one.

**Comment by aparcar** [comment]
isn't this covered by the firstboot wizard?

**Comment by ilario** [comment]
This is very epic stuff, can't we consider this problem addressed by network-profiles + Chef?

**Comment by aparcar** [comment]
I'm thinking of creating an interface to create network profiles online. Maybe integrated into chef

**Comment by ilario** [comment]
As @aparcar wrote more than one year ago, this is the work of FirstBootWizard. Closing.
