### ISSUE TITLE
Fix 11s support on Atheros chips

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#102]
In the current implementation of Atheros' 802.11s there seems to be a bug that hangs the kernel.
@p4u and @altergui may be able to add more detail to this issue.

**Comment by dangowrt** [comment]
/me is going to pick up a serious amount of ath9k test gear from @FreifunkUFO at some point during the weekend

**Comment by nicopace** [comment]
@dangowrt awesome!!! Let us know what you find out :)

**Comment by FreifunkUFO** [comment]
which firmware?
kernel-hangs? so we might need serial console?

**Comment by FreifunkUFO** [comment]
some freifunk-gluon users also uses 11s.. we have to ask them about their experiences and wifi-config.

https://github.com/freifunk-gluon/gluon

**Comment by dangowrt** [comment]
Looks like @nbd168 just fixed 802.11s in LEDE, at least that kernel bug does't get triggered any more.
See [commit cffeb311 mac80211: backport an upstream fix for queue start/stop handling](https://git.lede-project.org/?p=source.git;a=commit;h=cffeb31107e27a48ddaf4953590acdefc66f2de9)

**Comment by nicopace** [comment]
Are you sure @dangowrt? it doesn't seem to mention much more than 'Fixes issues with 802.11s'... we should test

**Comment by dangowrt** [comment]
It looks like it, but I'm about to test this excessively just now...

**Comment by FreifunkUFO** [comment]
ok, i found a ticket about this stuff: https://bugs.lede-project.org/index.php?do=details&task_id=644&order=dateopened&sort=desc

**Comment by FreifunkUFO** [comment]
and i found another ticket: https://bugs.lede-project.org/index.php?do=details&task_id=619&order=dateopened&sort=desc

**Comment by dangowrt** [comment]
#619 is the one which got fixed by the patch @nbd168 imported from
upstream (I referenced previously).\

#644 got an obviously wrong wifi config (option ifname is the most
likely cause of the probolem, coverage '5' seems wrong, too)

**Comment by p4u** [comment]
Fixed in the last release

**Comment by FreifunkUFO** [comment]
so why there is a need for an extra (gluon?-)snippet/patch?
https://github.com/libremesh/lime-sdk/blob/master/snippets/patch_sdk_11s.sh
its uploaded by anonymious!? :-o

**Comment by ilario** [comment]
anonymous = p4u, as he [confirmed](https://lists.libremesh.org/pipermail/lime-users/2017-May/000604.html) in lime-users mailing list

**Comment by p4u** [comment]
That was a mistake. I commited from another computer where my name was
not configured properly on git.

On 12/05/17 16:41, Ilario Gelmetti wrote:
> anonymous = p4u, as he [confirmed](https://lists.libremesh.org/pipermail/lime-users/2017-May/000604.html) in lime-users mailing list
> 

-- 
./p4u

**Comment by dangowrt** [comment]
See also https://github.com/libremesh/lime-packages/issues/123 which seems to be a duplicate of this bug for more details
