### ISSUE TITLE
Remove primary_interface unused option

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#1026]
In lime-defaults, there is a `primary_interface` option:
https://github.com/libremesh/lime-packages/blob/396c37ac8b853156e8c72dd51cb387736f4dc05c/packages/lime-system/files/etc/config/lime-defaults#L19

But it is currently not being used:
https://github.com/search?q=repo%3Alibremesh%2Flime-packages+primary_interface&type=code

So it should be removed for avoiding confusion.

**Comment by spiccinini** [comment]
It is used by primary_mac() that is used by primary_address() that is used in many places, or I am wrong?
