### ISSUE TITLE
Configuration for reserving IP ranges for static assignations

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#106]
Involves /etc/config/lime configs and LuCI interface implementation.

**Comment by ilario** [comment]
Specifying IP autoconfiguration range for LiMe nodes (already implemented) and DHCP range (still to implement, see #33) should be enough for leaving a free range for static IPs.

**Comment by nicopace** [comment]
This was a feature requested by @nicoechaniz . what do you think?

**Comment by ilario** [comment]
One month without comments, closing as duplicate of #33.
