### ISSUE TITLE
lime-app still uses $RANDOM in crontab

### ISSUE THREAD

**Issue by pony1k** [libremesh/lime-packages#1075]
These two scripts add lines to crontab that use ash `$RANDOM`, which does not work in OpenWrt 19.07 to OpenWrt 22.03.

- [shared-state-reference_state_nodes_info_cron](https://github.com/libremesh/lime-packages/blob/5053cf0cb46b7f865d9c3917c3b08232c88b66d1/packages/lime-app/files/etc/uci-defaults/shared-state-reference_state_nodes_info_cron)
- [shared-state-reference_state_wifi_links_info_cron](https://github.com/libremesh/lime-packages/blob/5053cf0cb46b7f865d9c3917c3b08232c88b66d1/packages/lime-app/files/etc/uci-defaults/shared-state-reference_state_wifi_links_info_cron)

Are these cronjobs still needed? Should they be repaired?

**Comment by ilario** [comment]
I start thinking that we have to abandon OpenWrt 22 and previous ones, as shared-state-async is not possible to compile on them.
And $RANDOM is available on OpenWrt 23 (https://github.com/libremesh/lime-packages/issues/800#issuecomment-1522950082) so we should eliminate random_numgen at some point and use only $RANDOM.
Do you agree?

**Comment by pony1k** [comment]
I agree. I can see no reason to use OpenWrt 22 or earlier on new installations.
