### ISSUE TITLE
[lime-proto-bmx6] bmx6hosts name resolution does not always work

### ISSUE THREAD

**Issue by nicoechaniz** [libremesh/lime-packages#118]
Depending on dnsmasq for resolution of [host].mesh names generated by the bmx6hosts script makes resolution unreliable because of known unstability of dnsmasq at the moment.

Proposal: have the bmx6hosts_dnsmasq_update cron job write bmx6hosts output to /etc/hosts directly, wrapped by markers (Eg. ###### autogenerated by bmx6hosts ######).

Reason: this is a last resort name resolution which should never fail.

**Comment by ilario** [comment]
This would be solved by #122 merge I suppose.

**Comment by nicopace** [comment]
yes, you're right! closing it! thanks for the housekeeping @ilario
