### ISSUE TITLE
Add link to libremap

### ISSUE THREAD

**Issue by p4u** [libremesh/lime-packages#120]
From /cgi-bin/luci/lime/location tab to libremap

**Comment by svalo** [comment]
I'd like to deal with this. Should the link point to http://libremap.net  or to something more specific to the community? 
Would it be fine to insert it between [L37](https://github.com/libremesh/lime-packages/blob/develop/packages/luci-app-lime-location/files/usr/lib/lua/luci/view/location/location.htm#L37) and [L38](https://github.com/libremesh/lime-packages/blob/develop/packages/luci-app-lime-location/files/usr/lib/lua/luci/view/location/location.htm#L38) with a text like 

'View the full map on [libremap.net](http://libremap.net) ?
