### ISSUE TITLE
Solve dhcp-lease-sharing performance issues

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#136]
notes: resolver performances dhcp-lease-sharing  <-- https://github.com/libremesh/lime-packages/issues/104

**Comment by ilario** [comment]
#104 sound unrelated, no?

**Comment by nicopace** [comment]
anyone can comment? @p4u @altergui @nicoechaniz ?

**Comment by ilario** [comment]
If there's no additional info I would close this issue.

**Comment by nicopace** [comment]
It's ok to close it apparently
