### ISSUE TITLE
Implement distributed dhcp leases (alfred, bmx6/7-sms) in odhcpd

### ISSUE THREAD

**Issue by dangowrt** [libremesh/lime-packages#150]
odhcpd offers much better integration and higher code quality than dnsmasq. Implementing lease sharing in odhcpd similar to the way it is currently implemented in dnsmasq to get rid of dnsmasq (which is a goal on the general OpenWrt/LEDE agenda)

**Comment by ilario** [comment]
related to discussion on #104

**Comment by ilario** [comment]
We're discussing whether to just stay with dnsmasq on #294.
Let's re-open this in case we decide to actually put effort into the migration.
