### ISSUE TITLE
hostname and ssid length are different

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#157]
when you change the name of the node, it truncks the ssid to a certain length and the hostname to another length.

expected behaviour: to be both the same

actual behaviour: names are different

**Comment by ilario** [comment]
Mh? Aren't hostname and ESSID independently defined?

**Comment by nicopace** [comment]
actually not. in lime we have a config were it is defined in the same place.
this is actually a very simple bug, but just left it with the 'quickfix' tag for any newcommer to be able to easily join and solve it :)

**Comment by ilario** [comment]
do you mean  that `option apname_ssid 'LibreMesh.org/%H'` is truncated to a different length than `option hostname 'LiMe-%M4%M5%M6'` when hostname is customized?
Do you have a clue about where does this happen?

**Comment by nicopace** [comment]
I don't konw where that is configured in /etc/config/lime ... i did it through the simple config->advanced->hostname LuCI interface

**Comment by altergui** [comment]
On 20/06/17 00:13, Nicolás Pace wrote:
> actually not. in lime we have a config were it is defined in the same place.
> this is actually a very simple bug, but just left it with the 'quickfix'
> tag for any newcommer to be able to easily join and solve it :)

maybe it's not a bug?

SSID is restricted to 32 characters length, that's why it's truncated
(else, AP with name doesn't come up)

hostname doesn't have that restriction, and it's used elsewhere (like
bmx6, dns, etc) so i'd leave it untruncated

**Comment by nicopace** [comment]
not a bug... maybe with the apname it is complex because it is prefixed with the network name, so it gets shrinked even more... 
I get it ... let's leave it that way.
Thanks for the input.
