### ISSUE TITLE
Stations visualization need to hide the vlans

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#158]
expected behaviour:
not to show the vlans in http://thisnode.info/cgi-bin/luci/status/stations

actual behaviour:
shows the vlans :(
![screenshot from 2017-06-14 22-38-57](https://user-images.githubusercontent.com/1136597/27151135-497ea40c-5152-11e7-8e28-5f25eae56e24.png)

**Comment by ilario** [comment]
Which is the default LEDE behaviour? To show them or not?

**Comment by nicopace** [comment]
I don't know which is the LEDE behaviour... this is the standard LibreMesh behaviour.

**Comment by ilario** [comment]
@nicopace updates? I feel that we cannot easily fix this in LuCI, no?

**Comment by ilario** [comment]
Help on this is welcome, but has low priority as we'll move from LuCI to lime-app. Closing.
