### ISSUE TITLE
firmware upgrade via webui

### ISSUE THREAD

**Issue by FreifunkUFO** [libremesh/lime-packages#161]
i have my tplink 850 with new official libremesh firmware from 4 days ago.
when trying firmware upgrade via webui to an even newer firmware i got errors:

/usr/lib/lua/luci/dispatcher.lua:460: Failed to execute call dispatcher target for entry '/lime/flashops/sysupgrade'.
The called action terminated with an exception:
/usr/lib/lua/luci/template.lua:74: Failed to load template 'admin_system/applyreboot'.
Error while parsing template '/usr/lib/lua/luci/view/admin_system/applyreboot.htm':
No such file or directory
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:460: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:141: in function </usr/lib/lua/luci/dispatcher.lua:140>

**Comment by p4u** [comment]
Is this error still appearing?

**Comment by FreifunkUFO** [comment]
im confused with libremesh domains and subdirectories.. 
which one is the most official libremesh testing firmware this week?

**Comment by nicopace** [comment]
repo.libremesh.org/lime-17.04/targets/

**Comment by p4u** [comment]
The last release firmware is always here: http://repo.libremesh.org/current/

**Comment by FreifunkUFO** [comment]
the firmware-files are 2 weeks old :-/ no changes/bugfixes on libremesh these weeks?

and, there ist more than one file per device/flavour, f.i.

http://repo.libremesh.org/current/targets/ar71xx/generic/tl-wr710n-v1/lime_default/lede-17.01.2-libremesh-ar71xx-generic-tl-wr710n-v1-squashfs-factory.bin
vs.
http://repo.libremesh.org/current/targets/ar71xx/generic/Default/lime_default/lede-17.01.2-libremesh-ar71xx-generic-tl-wr710n-v1-squashfs-factory.bin

**Comment by FreifunkUFO** [comment]
ok: firmware upgrade now runs without above issue

**Comment by FreifunkUFO** [comment]
not that nice webui style, but its running...
![simple-config-firmware-flash](https://user-images.githubusercontent.com/2579265/27809173-9f7ecbf2-604d-11e7-9727-926bd3dcb3ec.png)
