### ISSUE TITLE
Include router model in hostname

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#162]
Hostname can include router model for making easier the understanding of network representation in web ui.

**Comment by ilario** [comment]
Adding the router model in the hostname would make the identification of devices easier, for example in this BMX6 graph where I added manually the models.


![BMX6 network graph](https://lists.libremesh.org/pipermail/lime-users/attachments/20170617/c49719a2/attachment.png)

**Comment by FreifunkUFO** [comment]
so these hostnames contains spaces and will be very long?

**Comment by ilario** [comment]
It was mainly a concept, I can rephrase the issue title in "Include more node characteristics in default hostname".
The sanitized and truncated router model name is an option.

**Comment by ilario** [comment]
How can one get the router model from inside LEDE?
I mean something like `tl-wdr3600`.

**Comment by ilario** [comment]
This info can be obtained from `/tmp/sysinfo/model`.

**Comment by dangowrt** [comment]
speaking in shell, the ubus API allows you to

```
jsonfilter -s "$(ubus call system board)" -e "@.board_name"
```

obviously you can use other languages to call ubus and process the JSON output.

**Comment by ilario** [comment]
Nice!!
I have no idea why but on my router (Sagem F@ST2704N) there's info in `/tmp/sysinfo/board_name` but there's no board_name field in `ubus call system board` (there's a model field, but it's not as much compact).
Do you think it's incorrect to stick to 
Anyway, what's missing is just implement this in `utils.lua` as a function `applyBoardTemplate`, use it in `system.lua` and document it in `lime-example`

**Comment by ilario** [comment]
I perceive a non-interest on this topic, that's ok, closing.
