### ISSUE TITLE
unify releases at repo.libremesh.org

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-packages#164]
The 16.07 releases is missing a `targets` seperation
http://repo.libremesh.org/lime-16.07/
http://repo.libremesh.org/lime-17.04/targets/

Is that on purpose?

**Comment by ilario** [comment]
The whole path and organization is different... I have no idea why.
For example, for the same router and the two versions the paths are:
`http://repo.libremesh.org/lime-16.07/ar71xx/generic/openwrt-15.05.1-ar71xx-generic-tl-wdr3600-v1-squashfs-sysupgrade.bin`
and
`http://repo.libremesh.org/lime-17.04/targets/ar71xx/generic/tl-wdr3600-v1/lime_default/lede-17.01.2-libremesh-ar71xx-generic-tl-wdr3600-v1-squashfs-sysupgrade.bin`

**Comment by dangowrt** [comment]
I reckon this is due to `cooker` being introduced and several flavors for each device now being generated... Also note that 16.07 was still based on OpenWrt 15.05 which didn't have per-architecture packages, it used to build all packages for each target/subtarget rather than only the target-specific packages.

**Comment by p4u** [comment]
> I reckon this is due to cooker being introduced and several flavors for each device now being generated... Also note that 16.07 was still based on OpenWrt 15.05 which didn't have per-architecture packages, it used to build all packages for each target/subtarget rather than only the target-specific packages.

Right.

The community_chaos (lime-16.07) binaries were manually copied to repo.libremesh.org (which is the new server using  _cooker_) for legacy purposes only. The new directory structure is based on the LEDE directory structure [1].

[1] http://downloads.lede-project.org/releases/17.01.2/

**Comment by aparcar** [comment]
all right, thank you both for the clarification! I think this is solved
