### ISSUE TITLE
webui simple mode: "switch" tab appears, even when there is no switch

### ISSUE THREAD

**Issue by FreifunkUFO** [libremesh/lime-packages#171]
even when there is no switch
the "switch" tab appears atm
(webinterface, on "status" mode, without any login)

**Comment by FreifunkUFO** [comment]
with "administration" login the behaviour seems to be normal:
on "network" tab there is no "switch" link to click..

p.s. i tried that with tplink-710-v.2.1 (a.k.a. tplink-710-v1) where wan is eth0 and lan is eth1

p.p.s. its a very small bug, but please even take care of it!

**Comment by FreifunkUFO** [comment]
ping

**Comment by nicopace** [comment]
hehe... pinging doesn't make any progress on the issue... the stalebot has a bug :)
many of the devs (me included) are putting the ui efforts in lime-app, and phasing out the use of luci.
PR welcome, but no maintenance will happen, at least it is extremely low priority

**Comment by ilario** [comment]
I copy @nicopace: help on this issue is welcome but as by default we'll not include LuCI in the 19.something release, this issue has low priority.
Closing.
