### ISSUE TITLE
Unify LibreMesh release information

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-packages#181]
On standard LEDE I'm using `ubus call system board` and check the `release` section. On Libremesh a look at /etc/lime_release provides the information. Is it possible to modify the `ubus call system board` output to give the same information as lime_release does?

The most simple solution could be to modify the `/etc/openwrt_release` file or create a symlink from `lime_release` to `openwrt_release`

This issue is very important for the [attended sysupgrade](https://github.com/aparcar/gsoc17-attended-sysupgrade) I'm trying to implement. 

(This was send on `lime-dev` mailing list before)

**Comment by nicopace** [comment]
how would you suggest to solve it?

**Comment by aparcar** [comment]
> The most simple solution could be to modify the /etc/openwrt_release file or create a symlink from lime_release to openwrt_release

I could create a PR which auto overrides the `openwrt_release` file with LiMe data.

**Comment by nicopace** [comment]
Please do :)
