### ISSUE TITLE
Webui: add link to offline documentation in /www/docs

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#195]
[lime-docs](/libremesh/lime-packages/tree/master/packages/lime-docs) package includes documentation for offline use in LibreMesh firmware images.
The documentation is installed in /www/docs directory (with a symbolic link from /docs), so that it can be accessed by the http server.
A link has to be added in the [lime-webui](/libremesh/lime-packages/tree/master/packages/lime-webui) for accessing this documentation directory.

**Comment by pedro-nonfree** [comment]
I don't know what's the syntax being used (asciidoc?) but I think that in the website should render that format in something more web-based

**Comment by ilario** [comment]
AsciiDoc renderer is written in Python, AsciiDoctor renderer is written in Ruby. I believe that for obtaining HTML pages from AsciiDoc files, one of these two is needed but none can fit in a router.

If we really really want this, the only option I see is to download HTML pages from the website during lime-docs compilation.

**Comment by nicopace** [comment]
I would go for a progressive enhancement approach... a link for now would suffice.
Also, asciidoc was ment to be read in ascii, so we shouldn't bother much about that.
@ilario is that something u can do? (A menu option in luci for accessing the docs).

**Comment by ilario** [comment]
@nicopace I'm not knowledgeable with the web interface, maybe @gmarcos87?

**Comment by ilario** [comment]
@gmarcos87 do you think it's a good or a bad idea to have a documentation tab in the lime-app?

**Comment by nicopace** [comment]
I wouldn't add it like it is in the lime-app as it would create noise to the lime-app users without adding value.
The technical capacity traning part of lime-app needs to get thought through as a project in itself.
I wouldn't add it on the web, would just add a comment on the /etc/banner saying that there is documentation on the router, as most of the doc are more for a technical audience than they are for the average user.

**Comment by ilario** [comment]
> I wouldn't add it on the web, would just add a comment on the /etc/banner saying that there is documentation on the router

Ok, makes sense. New issue for this here: #616 
So now it does not make any sense that the docs are placed in /www/docs and linked in /docs, we can change also that.

**Comment by ilario** [comment]
> I wouldn't add it on the web

Ok, so in #675 I removed it from /www
