### ISSUE TITLE
Make safe-reboot aware if there is a backup or not

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#203]
If there is no backup, [safe-reboot](/libremesh/lime-packages/blob/develop/packages/safe-reboot/Makefile#L23) shouldn't remove the /etc overlay

**Comment by ilario** [comment]
Looking at the code [here](/libremesh/lime-packages/blob/develop/packages/safe-reboot/files/usr/sbin/safe-reboot#L105) seems that it already checks for the existence of a backup...

```
    if [ -s $file_etc_lastgood ] ; then
        safe-reboot discard
    fi
```

So is this check not working?

**Comment by nicopace** [comment]
Aparently...this was a bug I transcribed from the core team.
If you can't reproduce, just tag it and close it :)

**Comment by nicoechaniz** [comment]
I think it was @altergui who observed this when safe-reboot failed him in node nicojesigioia in QuintanaLibre. @altergui can you explain this further?

**Comment by altergui** [comment]
On 17/09/17 09:06, nicoechaniz wrote:
> I think it was @altergui <https://github.com/altergui> who observed this
> when safe-reboot failed him in node nicojesigioia in QuintanaLibre.
> @altergui <https://github.com/altergui> can you explain this further?

steps to reproduce:

do "safe-reboot discard" in a node (without having done "safe-reboot" first)

expected:
no action, error reported

actual result:
node dies

**Comment by ilario** [comment]
Ok, so what's missing is a check before the `rm -rf $dir_etc` line in safe-reboot.
