### ISSUE TITLE
Add automation for publishing packages to repo.libremesh.org

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#227]
Right now, packages are being published manually by @p4u .
Would be great to automate the process as a travis task.
This is what is being run right now:
https://github.com/libremesh/lime-sdk/blob/master/snippets/build_and_cook_all.sh

Create a travis task that runs this for each new release.
Define how a release branch is differenciated from any other branch.... probably because is a [0-9][0-9]\.[0-9][0-9]\(\.[0-9][0-9]\) label.

**Comment by ilario** [comment]
Any update on this? @aparcar do you have idea of the status of this?

**Comment by ilario** [comment]
This has been solved long time ago using continuous integration publishing compiled packages here:
https://snapshots.libremesh.org/packages/
Closing.
