### ISSUE TITLE
smonit should run also during init

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#242]
It's happening frequently on my router that dnsmasq-dhcpv6 doesn't start with the system so that I have to wait smonit to run (every 5 minutes) for having a DHCP server.
I propose to add smonit also as last process in init so that it's run just after the boot.

**Comment by ilario** [comment]
this issue is about creating a small init script running after all other init scripts and executing smonit

**Comment by G10h4ck** [comment]
I believe this should not be done, we risk to cause race conditions, as services being tested could be not yet ready and so running the *_fixes at that time could make the openwrt/LEDE init system crazy

**Comment by ilario** [comment]
Ok, any other solution?
Maybe we could decrease the interval time from 5 min to 2-3 min?
Or just check if 17.01.4 uses a good version of dnsmasq and move to that as soon as possible?
Anyway I reproduced this dnsmasq problem also running LibreMesh in a virtual machine, and dnsmasq never starts by itself.

**Comment by G10h4ck** [comment]
Please open or reference another issue for the specific dnsmasq bug
