### ISSUE TITLE
Update readme with Chef and contact channels

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#256]
* Add a tiny section mentioning the existence of chef and a link to the repository and official website.
* Either add Matrix channel in contacts or empty that section and leave just a link to http://libremesh.org/communication.html

**Comment by aparcar** [comment]
Should o add the matrix channel in chef rather then the mailing list?

**Comment by ilario** [comment]
Matrix channel is not going to be included, see #412 
Chef is being included in #437
