### ISSUE TITLE
Implement wpad-mesh-nocrypt package

### ISSUE THREAD

**Issue by p4u** [libremesh/lime-packages#268]
Using wpa_supplicant over a mesh WiFi interface gives the option to use channel auto selection and DFS restricted channels.

To this end, a modified copy of wpad-mesh might be created as a libremesh package removing the crypto related dependencies.

**Comment by aparcar** [comment]
@dangowet works on a smaller version called wpad-mesh-wolftls. We should check the size impact and may move.

**Comment by aparcar** [comment]
@p4u please see the package wpad-mesh-wolfssl, wolfssl should already be much smaller then the openssl libary. Can we close this?

**Comment by ilario** [comment]
I think that after @aparcar comment, we can move the discussion on whether include wpad-mesh-wolfssl by default, see #613. Closing this.
