### ISSUE TITLE
Reduce log verbosity of dnsmasq

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#279]
Now dnsmasq is outputing a lot of unnecesary debugging information to syslog.
In order to stop this from happening, I would like to propose to add to the default /etc/config/dhcp file generated by lime-config the following option
```
dhcp.@dnsmasq[0].quietdhcp='1'
```
that way dnsmasq reduces its verbosity.

cc @nicoechaniz

**Comment by ilario** [comment]
IMHO _dnsmasq_ originates the main stability problem in current stable release (#273 #243 #242 #111). I would not decrease its log level before solving.

**Comment by ilario** [comment]
Do you agree with me? Is it ok to close this? @nicopace @nicoechaniz
