### ISSUE TITLE
safe-reboot: Add notification to all console users that safe-reboot is running

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#310]
If safe-reboot is running it is hard, even for the same user that is using it, to know when it will reboot the system.

It would be great if it can notify all users connected that it will reboot the system and how to prevent it or react to it.

I think it could be added here:
https://github.com/libremesh/lime-packages/blob/feb3b8996fe8e008ff391dd6feef9a6f11225dfa/packages/safe-reboot/files/usr/sbin/safe-reboot#L100

This is the function that it could use to notify:
```bash
function message_to_all_loggedin_users {
  message="$1";
  for pts in `ls /dev/pts/`; do
    echo "$message" > /dev/pts/$pts;
  done;
}
```

**Comment by gmarcos87** [comment]
**SIDE NOTE**
With almost the same code we could notify users logged in on the node that another user entered.
This prevents users from changing the settings between them without knowing it.

**Comment by ilario** [comment]
@nicopace did you see #238 ?

**Comment by nicopace** [comment]
Haven't seen, sorry!
Closing duplicate!
