### ISSUE TITLE
Feature request: olsr-auto-gw-mode

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#32]
Just a reminder: 
we need a package equivalent to _batman-adv-auto-gw-mode_ and _bmx6-auto-gw-mode_ working for OLSR.

**Comment by FreifunkUFO** [comment]
f.i. check the years-old freifunk gw-check: https://github.com/openwrt/luci/blob/master/contrib/package/freifunk-gwcheck/files/usr/sbin/ff_olsr_test_gw.sh

**Comment by nicopace** [comment]
@ilario is this still needed? the issue has some time around and had noone to take care of it...

Could it be that there are no users that need it?

**Comment by ilario** [comment]
Yep, that's the case, up to now we have no user (AFAIK) who is using OLSR or OLSR2.
That's a pity 'cause it's implemented, except for auto-gateway.
Back then we supposed people from Ninux in Italy would have needed this.
@gabri94 any opinion of this?

**Comment by gmarcos87** [comment]
None of the stakeholders took the initiative. I close this until there is a real demand for this feature. The issue was opened more than three years ago.
