### ISSUE TITLE
Feature request: Specify DHCP range

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#33]
Hi!
I want to compile a Libre-Mesh firmware image which contains a custom IP range (= 10.37.192.1 - 10.37.255.254) for the DHCP server.
To specify this in the feeds/lime/packages/lime-system/files/etc/config/lime-defaults would be optimal.
Up to now the workaround is to modify the start (= 49152) and limit (= 16382) options in packages/network/services/dnsmasq/files/dhcp.conf which will end up to be /etc/config/dhcp.
Thanks,
Ilario

**Comment by G10h4ck** [comment]
Wasn't this solved by your pull request some time ago?

**Comment by ilario** [comment]
No, absolutely. The problem is still there.

**Comment by ilario** [comment]
In LiMeCat2016q3 we discussed this and decided that `/etc/config/lime*` files are just for "one to many" settings (with a few exceptions like hostname), so in this case writing directly in /etc/config/dhcp is not harder than writing in /etc/config/lime.

**Comment by ilario** [comment]
We discovered that writing to `/etc/config/dhcp` is now enough as the DHCP range has been defined in 3a6596d as the full broadcast domain in anygw package.

**Comment by nicopace** [comment]
@ilario you said tha was enougth, but you reopened the issue!
What was missing?
There is also a related issue #106

**Comment by ilario** [comment]
@nicopace the DHCP range is still hardcoded in anygw code (see above), I didn't dare to try coding something for changing this...
Now you just can't change the DHCP range, that's why I reopened the issue :)

**Comment by nicopace** [comment]
Get it ... let's see what happens with #106

**Comment by ilario** [comment]
I see the thing the other way around: let's fix this and #106 will be automagically fixed also.

**Comment by nicopace** [comment]
Yeah... you are right @ilario... in fact, it seems this one and #106 are duplicates, right?

**Comment by ilario** [comment]
In my opinion yes :)

**Comment by ilario** [comment]
The anygw code changed but looks the issue is still there (to be verified that /etc/config/dhcp is still ignored), specifically the value is set in these two lines introduced in f40accd:
```
uci:set("dhcp", "lm_net_br_lan_anygw_dhcp", "start", "2")
uci:set("dhcp", "lm_net_br_lan_anygw_dhcp", "limit", (2 ^ (32 - anygw_ipv4:prefix()))) -- use whole network
```

**Comment by ilario** [comment]
Do you think it's ok to add a couple of options like `anygw_dhcp_start` and `anygw_dhcp_limit` to network section in `/etc/config/lime-defaults`?
An alternative is to set this with the subnet notation (like an `option anygw_dhcp '10.%N1.128.0/17'`).

**Comment by ilario** [comment]
I propose an **untested** solution in #222.

**Comment by ilario** [comment]
An alternative would be to encourage users to customize values in `/etc/config/dhcp`. Taking the raw configs directly from there would allow users to use other options currently unavailable with anygw, for example static DHCP leases.

**Comment by ilario** [comment]
Don't you think a similar option should be implemented for IPv6?
