### ISSUE TITLE
bmx7 iwinfo bandwidth estimation with autoconf wifi-iface

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-packages#335]
bmx7 offers a plugin to read the output of `iwinfo` and give a better estimation of the possible bandwidth. This doesn't work for now as LiMe configures the interfaces in a way that iwinfo/bmx7 doesn't detect them as wifi interface. We should think of a solution to offer more precise estimations of link quality. 

```
root@smpl-monitor:~# bmx7 -c interfaces
INTERFACES:
dev           state linkKey    linkKeys          type     channel rateMax idx localIp                     rts helloSqn rxBpP   txBpP   
wlan1-mesh_13 UP    DH2048M112 RSA896,DH2048M112 ethernet 0       54000K  2   fe80::6f0:21ff:fe33:db02/64 2   43463    382/2.5 196/1.3 
```
```
root@smpl-monitor:~# iwinfo 
wlan1-mesh ESSID: unknown
          Access Point: 00:00:00:00:00:00
          Mode: Mesh Point  Channel: 165 (5.825 GHz)
          Tx-Power: 17 dBm  Link Quality: 70/70
          Signal: -20 dBm  Noise: -95 dBm
          Bit Rate: 40.6 MBit/s
          Encryption: unknown
          Type: nl80211  HW Mode(s): 802.11abgn
          Hardware: 168C:002A 168C:3099 [Generic MAC80211]
          TX power offset: unknown
          Frequency offset: unknown
          Supports VAPs: yes  PHY name: phy1
```

@axn what do you suggest?

**Comment by dangowrt** [comment]
I reckon you'll have to do something like here
https://github.com/freifunk-gluon/gluon/commit/4ce85afc22a2c64e5ac5ea1b52ad93f323e384d4
in the iwinfo plugin to first climb down to the 'physical'
interface.

**Comment by axn** [comment]
Thx Daniel and Paul, I'll work that out...
/axel

**Comment by aparcar** [comment]
https://github.com/bmx-routing/bmx7/pull/12

**Comment by dangowrt** [comment]
@aparcar please test if https://github.com/bmx-routing/bmx7/pull/15 fixes the problem

**Comment by aparcar** [comment]
now that bmx7 detects devices and speed correctly we should disable the max rate per default as the routing protocols decides it based on the actual situation. I'd suggest to disable the settings of rateMax if no specific rate is set.

@G10h4ck @p4u @dangowrt
