### ISSUE TITLE
add new languages to dropdown menu

### ISSUE THREAD

**Issue by patogit** [libremesh/lime-packages#360]
where is the file that controls the interface language selection dropdown menu on the System > System page in the "Language & Style" tab?

**Comment by nicopace** [comment]
I guess this is a thing of OpenWRT/LuCi, not ours, but we can override their setting if we want.

Also, would be cool to add a dropdown menu on the top of the site to be able to change language at each session.

**Comment by patogit** [comment]
> I guess this is a thing of OpenWRT/LuCi, not ours, but we can override their setting if we want.

so it might be somewhere in [the luci code on github](https://github.com/openwrt/luci/tree/master)?

> Also, would be cool to add a dropdown menu on the top of the site to be able to change language at each session.

I agree!

**Comment by nicopace** [comment]
It looks like you are right!
Don't have the mental space to try it, but if you want to do a VM with this, you can use my instructions here: https://blog.freifunk.net/2017/07/22/streamline-app-development-openwrt/
(found them after searching for some time @gmarcos87 comments... and I did that documentation! duh!)

**Comment by nicopace** [comment]
Marcos provides his link also: https://github.com/gmarcos87/lime-virtualbox

**Comment by patogit** [comment]
@gmarcos87 instructions look helpful, if I install VirtualBox, which I would rather avoid in order to save disk space and bandwidth (I'm on a really slow connection at the moment).

@nicopace your instructions leave me wondering if it worked or not, because of the line:
> With that last config and using an ui option in virt-manager, I was able to access the usb device TP-Link TL_WN822Nv1 on the Virtual Machine, but I was not able to use it yet because of driver problems.

I already have virt-manager with LXC installed on my system (Manjaro, based on Arch) Any hints on how to do this with virt-manager and LXC? I don't have virt-bootstrap installed. My root directory only has 300MB left (I'll increase it, but not today), so installing large packages isn't an option.

**Comment by nicopace** [comment]
Haven't done it in a while.
Would say go for Marcos solution and if it does not work I can check that again.

**Comment by patogit** [comment]
I installed VirtualBox, and got the image to boot to the console, and got the IP, but the LuCi interface doesn't load in my browser (even though in the LuCi interface for other nodes on the network, the VM node shows up on the list of mesh nodes).

I ran the `packages/lime-webui/build_i18n.sh` script , which gave some errors and generated some files, and I committed those files and submitted a pull request https://github.com/libremesh/lime-packages/pull/388, even though I haven't been able to test since I don't have a working VM and don't want to risk bricking a router.

**Comment by patogit** [comment]
This files seems relevant too:
https://github.com/libremesh/lime-packages/blob/b5681f4e8985aab0735b2a4d8f682a2cfb65fcf4/packages/lime-webui/Makefile

It defines Spanish, Portuguese, and German language support packages... but as far as I know the only language options so far have been English and Spanish. It was last edited 9 months ago in September.

**Comment by patogit** [comment]
This issue is now almost six months old, waiting until the Docker setup is functional.

**Comment by ilario** [comment]
@patogit you can try with QEMU+Virt-Manager, as described [here](https://github.com/libremesh/lime-sdk/blob/f49d4df32d9d63d196af61a5fbe3c1f15f7ad5d5/README.md#testing-on-qemu) (actually for me is not working and I don't know why... @svalo ideas?) that should also allow you to open the web interface.

**Comment by ilario** [comment]
This issue is related to the LuCI web interface, right?
In the next 19.something release we're going to ship lime-app by default (seems) and there's no language selection menu there.
Correct me if I'm wrong and feel free to re-open.

**Comment by nicopace** [comment]
We should update it to add a language config in lime-app.
It could be in the first screen, and as the first option in the menu, so it is always accessible.
@gmarcos87  what do you think?

**Comment by ilario** [comment]
> We should update it to add a language config in lime-app.
> It could be in the first screen, and as the first option in the menu, so it is always accessible.
> @gmarcos87 what do you think?

Actually I realised that lime-app automagically uses the language suggested by the browser (or something equally magical).
