### ISSUE TITLE
GroundRouting: connecting internet with static IP

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#367]
USECASE: ISPs that give static ips instead of dhcp in the network.

Expected behaviour: the app to allow the user to set the ip.

**Comment by G10h4ck** [comment]
I believe groundrouting is not related to this usecase

**Comment by nicopace** [comment]
Many of the conversations we have been having about how to reimplement groundrouting using media detection (mainly with @nicoechaniz ) include detecting what happens on the other side of the wire for every wire that is connected.
that is, if there is a dhcp server, if there is another libremesh device, or if there is none, and how to proceed with each.

**Comment by ilario** [comment]
So it would be something like an **automatic** configuration for ground routing?

**Comment by nicopace** [comment]
that is what was talked... but no progress on this yet... any volunteer @ilario  ;)

**Comment by ilario** [comment]
@nicopace reading again the original description of the issue, sounds more like #429, right?
Autoconfiguration of groundrouting sounds like something too epic to do (we usually refer with "groundrouting" to a very specific thing).

**Comment by ilario** [comment]
This issue is not clearly defined, I'm closing. Please feel free to re-open explaining it better. If it was actually a duplicate of #429, please reopen that issue instead of this one.
