### ISSUE TITLE
Evaluate DDHCPD as alfred replacement

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-packages#369]
[DDHCPD](https://github.com/sargon/ddhcpd) could do some work for us automatically, couldn't it?

We should evaluate that and may do a migration do get rid of various existing problems.

**Comment by nicopace** [comment]
@nicoechaniz

**Comment by aparcar** [comment]
This could remove the need of dnsmasq-lease-share, I'll set up a test config and share it here

**Comment by nicopace** [comment]
We need efficient mesh data distribution for many things (leases, dns, pitbull authorized macs, messaging, ...).
We need to abstract this in order to have it no matter what changes we do with the routing protocols.
@G10h4ck is this happening now?

**Comment by aparcar** [comment]
So what do?

**Comment by ilario** [comment]
[shared-state](https://github.com/libremesh/lime-packages/tree/master/packages/shared-state) has been implemented 7 months ago and replaces Alfred. Closing.
