### ISSUE TITLE
LiMe > Collections empty

### ISSUE THREAD

**Issue by 1am** [libremesh/lime-packages#372]
Hello

I'm trying to add LibreMesh to my existing build and after adding package feeds from https://github.com/libremesh/lime-packages or https://github.com/libremesh/lime-packages;develop (which is pretty much the same) I don't see any options to select in "LiMe > Collections" though there's multiple options available in LiMe section and the "Collections" subsection is visible.

I was aiming into installing https://github.com/libremesh/lime-packages/tree/develop/packages/lime-full so I've checked if the packages from [DEPENDS](https://github.com/libremesh/lime-packages/blob/develop/packages/lime-full/Makefile#L26) are ok - which they are - but still Collections is empty.

Searching for the "lime-full" package in menuconfig finds it but after navigating to it I get the same result - collections is empty.

Is this normal? I don't see anything exotic in the lime-full makefile which would cause Buildroot to hide away a package.

I'm building for Artheos AR7xxx/AR9xxx target, Generic subtarget with default profile and squashfs target image.

Anyone has maybe experienced this before?

**Comment by aparcar** [comment]
I'm not sure but `lime-full` requires `lime-base` requires `lime-proto-anygw` which [requires to deselect dnsmasq](https://github.com/libremesh/lime-packages/blob/develop/packages/lime-proto-anygw/Makefile#L25)

Maybe the same problem as here: https://github.com/libremesh/lime-packages/issues/104

But just a guess

**Comment by 1am** [comment]
Thank you for your time. This was exactly this. I've deselected previously dnsmasq but probably restored it afterwards.
