### ISSUE TITLE
Proposal: Simple reporting command for helping debug

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#423]
Just an idea: it could be useful to have a command for helping bug reporting.
This would get debugging info from various sources and output it in an agglomerated form, optionally to a file.
It could be included in the `lime-debug` packages.

A list of data that could be included:

- /etc/config/lime (removing passwords)
- /etc/config/lime-defaults
- /etc/config/network
- /etc/config/wireless (removing passwords)
- dmesg
- batctl if
- batctl o
- bmx6 -c show=status show=interfaces show=links show=originators show=tunnels
- free
- ps
- ip address show
- ip route show
- brctl show
- ip link show
- /proc/cpuinfo
- df
- logread -l 20 -f
- iw dev wlan0-mesh station dump
- iw dev wlan1-mesh station dump
- iw dev wlan0-mesh mpath dump
- iw dev wlan1-mesh mpath dump

Additional interesting data can be:

- LibreMesh and OpenWrt version
- BATMAN adv logs, maybe it can be to retrieve with `batctl loglevel all; batctl log; batctl loglevel none`?
- ...?

**Comment by aparcar** [comment]
Not bad, should I implement that?

**Comment by ilario** [comment]
Up to you :)
I would make the command in a way that without arguments prints everything to STDOUT (so that it can be piped to sprunge or copied and pasted) and if an argument is given everything is saved in a file with that name.

**Comment by ilario** [comment]
This is an example of a situation where even with all the aforementioned data I cannot understand why neither BATMAN adv nor BMX6 can see the peers over established IEEE802.11s links:

https://lists.libremesh.org/pipermail/lime-users/2018-November/001331.html

Which piece of information are we missing?

**Comment by aparcar** [comment]
We could setup something like debug.libremesh.org using https://github.com/solusipse/fiche
The rest is quite easy, I'll setup a package within the next days

**Comment by aparcar** [comment]
https://github.com/libremesh/lime-packages/pull/457/files
