### ISSUE TITLE
lime-librenet6 package missing title?

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#424]
A user reported that compilation with lime-sdk throws an error about lime-librenet6:
```
Makefile:33: *** Package/lime-librenet6 is missing the TITLE field.  Stop.
```
I suspect that removing the `/Default` string [here](https://github.com/libremesh/lime-packages/blob/17.06/packages/lime-librenet6/Makefile#L11) could fix this. But I did not test yet.

On a side note: why lime-librenet6 is present in 17.06 branch but not in master?

**Comment by ilario** [comment]
@aparcar @G10h4ck why isn't this package also in master branch? Has it been obsoleted by something else?

**Comment by G10h4ck** [comment]
I requested modification in the PR, but they where never made. It is in the other branch because @nicopace merged it by error and we never reverted it

**Comment by ilario** [comment]
Got it, you refer to the merge of #400. 
Your comments are in an open issue on #579

**Comment by ilario** [comment]
Is librenet6 still functional? Anyway the package is not in the master branch. Closing.
