### ISSUE TITLE
Cannot access nodes via primary IP

### ISSUE THREAD

**Issue by tomjones1977** [libremesh/lime-packages#431]
Hostname | sdh-rocket-m5
Model | Ubiquiti Rocket M XW
Firmware Version | LiMe 17.06 DaybootRely (17.06 rev. a1c5c4c 20180802_1339) / LuCI openwrt-18.06 branch (git-18.320.63580-3787301)
Kernel Version | 4.9.120

Occasionally I cannot access the nodes via their advertised IPv6 addresses on the BMX...Nodes list.  Accessing the web interface by host name, or 2a00 based IPv6 or even IPv4 works fine, but this requires manual work rather than clicking through from the node list.

**Comment by ilario** [comment]
Related to libremesh/lime-sdk#93

**Comment by ilario** [comment]
As the next release will be based, by default, on Babeld+Batman-adv rather than BMX6+Batman-adv, I think this became a low importance issue.
Still, images with BMX6 can be compiled and used, so if anyone wants to dig into this issue, is welcome!
