### ISSUE TITLE
fft-eval: package not arch independent

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-packages#473]
Hi @spiccinini , the fft-eval package isn't arch independent while our CI only compiles for mips. Usually this isn't a problem as we use Lua code, but compiling for every arch a C tool takes to much time. Could you consider creating a PR to add fft-eval to the official OpenWrt repo? Their build bots take care of the rest.

**Comment by spiccinini** [comment]
Hi! Another option that I think I prefer is to port the code to Lua, as we only use one function. I really don't know if fft-eval is common enough to add to the official OpenWrt repo, do you know?

**Comment by aparcar** [comment]
I'd recommend to push it to the official builds, that's whats supposed to happen with all LibreMesh related packages in some distant future...

**Comment by gmarcos87** [comment]
I never did the process of adding a package to openwrt repos. Do you want to try it @aparcar ?

**Comment by aparcar** [comment]
https://github.com/openwrt/packages/pull/8265

**Comment by aparcar** [comment]
Package was accepted upstream

**Comment by aparcar** [comment]
The package is still not available upstream as the compilation requires a special kernel option, which is unlikely to be accepted upstream. Maybe the package shouldn't be a hard dependency for lime-app

**Comment by gmarcos87** [comment]
Ok, let me adapt the lime-openairview code so that it only executes the code if the fft-eval package is installed.
I would also like to move fft-eval into a separate repository to keep it available.

**Comment by aparcar** [comment]
It's available in the openwrt sources, tho not compiled by default




Fri Sep 06 10:20:21 HST 2019 Marcos Gutierrez <notifications@github.com>:

**Comment by aparcar** [comment]
Please let me know once you updated the app. I'll then start building snapshot images.

**Comment by gmarcos87** [comment]
@aparcar fft-eval is removed in master now
