### ISSUE TITLE
DHCP Server on Nodes

### ISSUE THREAD

**Issue by kleper** [libremesh/lime-packages#483]
Hello,
I am trying to deactivate the DHCP server of each of the nodes that I have with LibreMESH, I have tried modifying the configuration files of lime-default but something has not gone well and I had to reinstall the firmware.

Thank you.

**Comment by aparcar** [comment]
>  But, @kleper, could you re-write the issue on lime-packages which is the proper repo for configuration issues?

Done via this new GitHub feature

**Comment by ilario** [comment]
Wowow @aparcar is [the new grua](https://www.tebeosfera.com/publicaciones/no_aparcar_llamo_grua_1991_bou.html)!

**Comment by ilario** [comment]
I recall I saw some network-profiles doing this in a brutal brutal way:

https://github.com/libremesh/network-profiles/blob/07eb7730bc8bd66471cfc21d74ab0ab5ef686e5f/trans.hackmeeting.org/L2nodes/etc/uci-defaults/disable_dhcp#L4-L10

https://github.com/libremesh/network-profiles/blob/07eb7730bc8bd66471cfc21d74ab0ab5ef686e5f/trans.hackmeeting.org/L2nodes/PACKAGES#L3-L5

Would it be an ok solution for you @kleper ?

**Comment by kleper** [comment]
Yes, this configuration works well for me.
Thank you very much.
