### ISSUE TITLE
lime-proto-anygw missing

### ISSUE THREAD

**Issue by PolynomialDivision** [libremesh/lime-packages#497]
The LiMe → lime-proto-anygw is missing? I followed the [compile](https://libremesh.org/development.html) instructions.

**Comment by aparcar** [comment]
Did you deselect `dnsmasq`? As far as I remember it the most common problem if *stuff is missing*

**Comment by PolynomialDivision** [comment]
Yep. Maybe something went wrong while compiling. :/ I will retry.

    ./scripts/feeds install lime-proto-anygw
    WARNING: Makefile 'package/feeds/libremesh/altermap-agent/Makefile' has a dependency on 'luci-lib-core', which does not exist
    WARNING: Makefile 'package/feeds/libremesh/lime-basic-uing/Makefile' has a dependency on 'lime-webui-ng', which does not exist
