### ISSUE TITLE
Piranha is blocking thisnode.info requests

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#519]
**What I expect to see**: in a newly flashed device with piranha package installed, if I go to thisnode.info I expect to see the luci interface

**What I actually see**: It redirects to piranha page.

**Comment by luandro** [comment]
If you're using https://github.com/LibreRouterOrg/openwrt it doesn't come with luci, that might be why.  The images we use in Moinho we've added luci and thisnode.info works fine.

**Comment by G10h4ck** [comment]
@nicopace as asked earlier in chat, did you tested if it is a matter of thisnode.info being resolved to wrong IP?

**Comment by nicopace** [comment]
nope, we couldn't test.
will try to test again, as well as the luci thing, but can't promise soon.

**Comment by gmarcos87** [comment]
@luandro any new? Or we can close this

**Comment by luandro** [comment]
Guess we can close right? What happens and is expected is that thisnode.info is directed to Lime App.
