### ISSUE TITLE
list channel_5ghz lime-config error

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#528]
Reported by @nicoechaniz:

Setup:
an /etc/config/lime file with a single list channel_5ghz entry in a 5ghz single radio device.

Expected behaviour:
to use the value provided in the config for the only 5ghz radio available.

Actual behaviour:
after doing `lime-config; lime-apply` the config applies a channel 52 to the only 5ghz radio available.

**Comment by ilario** [comment]
Waht...?
Can anyone check if this happens also after the merge of #603?

**Comment by ilario** [comment]
Closing as this is likely invalid after #603.
