### ISSUE TITLE
droped packets from babel vlan iface

### ISSUE THREAD

**Issue by spiccinini** [libremesh/lime-packages#580]
When using netperf from a node through the babel interface the throughput is almost 0. Ping does not work when using a size bigger than 1470. Using `mtu = 1496` seems to fix this issue.
To reproduce the problem:
With two LibreRouters. LR-A connected through WAN to "internet". LR-B connected to LR-A with LAN port to LAN port of LR-A. In this scenario pinging from LR-B to internet with ping -s SIZE 192.168.1.1 only works when SIZE <= 1470.

**Comment by G10h4ck** [comment]
Grrrrrrrrrrrrr  I saw something similar too in the past and told Felix!! He was reassuring saying that the drivers are capable to handle a few bytes more then the MTU for the sake of vlans... but your experience is not the case as I tought before talking with him...
