### ISSUE TITLE
FirstBootWizard: doesn't see a network

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#589]
What I expect to happen:
* when I open the FirstBootWizard I want to see the existing networks around me. In particular, from ql-roxa want to see ql-nicojesigioia

What I see:
* If I ssh to the node, I can see the adhoc networks provided by the node. If I directly connect to the neighbouring node, I can see that is sharing its lime-defaults file. but if I enter the lime-app firstbootwizard screen it doesn't show this node as an option (it actually says there is noone around).

How to reproduce it:
* flash a node with the current librerouterorg/openwrt image of libremesh: point it to ql-nicojesigioia

**Comment by gmarcos87** [comment]
Nico, I told you, you can't try fbw with quintanalibre. For many reasons, but surely what happened to you is related to the use of TZ channels on the network and not on the new device.

**Comment by nicopace** [comment]
Awesome, just wanted to keep track of the issue so we were not forgetting it (mainly I)... will dig into it tomorrow...

**Comment by markbirss** [comment]
@gmarcos87 this relates to my email sent, I will ask here about my issue

config-sharer-server package ? this is misspelled ?

I have compiled a fresh openwrt image from source added lime-app on 2 nodes
created a network on the 1 device but the other device cannot find the created network

**Comment by spiccinini** [comment]
@markbirss Which device are you using? AFAIK firstbootwizard only searches 5GHz mesh networks.

**Comment by markbirss** [comment]
@spiccinini
Ok, thank you for your feedback,  will check again with couple Aruba AP-105 and Meraki MR24's

was using a Aruba AP-105 (2.4/5Ghz) and GLI-Net USB150 (2.4Ghz)

regarding that package what is config-sharer-server ?

**Comment by markbirss** [comment]
Ok, I'm still having issue after creating a configured node not being able to scan for it. It seems the configuration is somehow broken.

**Comment by ilario** [comment]
I suppose this can be explained with #661 so I will close this as a duplicate.
Feel free to re-open it if you disagree! :)
