### ISSUE TITLE
bandwidth-test doesn't show help menu

### ISSUE THREAD

**Issue by gmarcos87** [libremesh/lime-packages#590]
In this pull-request https://github.com/libremesh/lime-packages/pull/573#discussion_r322632826 we realized that the -h option of the script is not working.

## Expected behavior
Display help menu with both __bandwidth-test -h__ and __bandwidth-test hakuna matata__

## Current Behavior
With either of the two options, it begins to perform bandwidth measurements.

**Comment by ilario** [comment]
Thanks, I already pushed the fix on my repo but I forgot to do the PR. Doing it now.
