### ISSUE TITLE
List of 5 GHz channels and one or two radio devices

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#602]
The current [implementation of the list of channels](https://github.com/libremesh/lime-packages/blob/69ed489fc771cbd3bd4e0047ba2c926e98304ce8/packages/lime-system/files/usr/lib/lua/lime/wireless.lua#L119-L122) (you can specify a list of wifi channels instead of a single channel, then each radio on the same band should receive a different channel, [currently this is active by default](https://github.com/libremesh/lime-packages/blob/69ed489fc771cbd3bd4e0047ba2c926e98304ce8/packages/lime-system/files/etc/config/lime-defaults-factory#L47-L48)) is troublesome when considering networks with mixed one and two radios devices.

Let's take an example using the current default configuration and two commonly employed routers:

* LibreMesh on TP-Link WDR3600: `wlan0` has channel 11 on 2.4 GHz band, `wlan1` has channel 48 on 5 GHz band
* LibreMesh on Ubiquiti NanoStation M5: `wlan0` has channel 157 (if country code is ok, see #594) on 5 GHz band

one would expect the two routers to connect each other using the 5 GHz radios, but this does not happen because of the channels.
Is it intentional? To me it looks like a bug.

**Comment by G10h4ck** [comment]
can you show the configuration file?

**Comment by ilario** [comment]
> can you show the configuration file?

I don't have the routers with me now, but the lime-defaults was the one from [lime-defaults-factory](https://github.com/libremesh/lime-packages/blob/7cd89460c80008e2cc7d2f1f539cbb0c3f87ece8/packages/lime-system/files/etc/config/lime-defaults-factory#L47-L48) and the example used above is exactly what happened.
This is not surprising as the implementation is using the `wlan#` number for indexing the channels list.

**Comment by G10h4ck** [comment]
With the current implementation either you use radio specific config section, or it behave like you described

**Comment by ilario** [comment]
Yess, what I mean is that with the _default_ configuration the behaviour should not be this weird.

So, IMHO either we change the implementation of the channels list or we leave just one channel in the _default_ configuration.

**Comment by ilario** [comment]
@spiccinini @G10h4ck do you think we can implement this feature in a better way?
For example considering either the 5 GHz or the 2.4 GHz radios instead of all of them?

**Comment by spiccinini** [comment]
Yes, I think a better implementation is to count independently the radios in each band.
