### ISSUE TITLE
Have an upgrade mechanism that maintains minimum configs for nodes

### ISSUE THREAD

**Issue by spiccinini** [libremesh/lime-packages#621]
The idea is  that after running  safe-upgade or sysupgrade we can maintain a minimum set of configs for a node: name, community name, location, hostkey, autorized_keys, ...

**Comment by ilario** [comment]
Isn't this lime-sysupgrade? (I never used it, but looks like what you're looking for)
https://github.com/libremesh/lime-packages/blob/master/packages/lime-system/files/usr/bin/lime-sysupgrade

**Comment by spiccinini** [comment]
Yes, also now that configurations are not polluted automatically then `sysupgrade foo.bin` should work as expected even if the default settings of libremesh are changed because the backup will be of lime-node and lime-community only.
