### ISSUE TITLE
lime-location nodes_and_links only works with adhoc

### ISSUE THREAD

**Issue by spiccinini** [libremesh/lime-packages#642]
If using 80211s then the links are always empty

**Comment by ilario** [comment]
Nice catch!
Looks like this grep is the issue:
https://github.com/libremesh/lime-packages/blob/b722f921dca901c508afc3fb080e7f7e674c143b/packages/ubus-lime-location/files/usr/libexec/rpcd/lime-location#L72

maybe it's enough to replace `grep adhoc` with `grep 'adhoc\|mesh\|apbb'`?
For the client interfaces, they have the same `-sta` suffix both if they're used for WAN or for backbone (for APbb and client in backbone see #554).
