### ISSUE TITLE
Update lime-proto-bgp BIRD dependencies

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#645]
With OpenWrt 19.07 the packages `bird4` and `bird6` does not exist anymore: they have been merged into a package named `bird1`.
A new version of that appeared with the name of `bird2`.

**Comment by ilario** [comment]
@g10h4ck could you check this out please?

**Comment by G10h4ck** [comment]
no time/means for that right now :-\

**Comment by a-gave** [comment]
it seems that OpenWRT 19.07 keeps the previous packages bird4 and bird6
it has renamed them to bird1-ipv4 and bird1-ipv6

so it's temporary fixable if changing (at line 24)
./package/feeds/libremesh/lime-proto-bgp/Makefile 
with:
#  DEPENDS:=+bird4 +bird6 +lime-system +lua
  DEPENDS:=+bird1-ipv4 +bird1-ipv6 +lime-system +lua
 
NOT tested, but it should probably works, and this issue can be renamed to 
"Update lime-proto-bgp BIRD2 dependencies"

**Comment by ilario** [comment]
> it seems that OpenWRT 19.07 keeps the previous packages bird4 and bird6
> it has renamed them to bird1-ipv4 and bird1-ipv6
> 
> so it's temporary fixable if changing (at line 24)
> https://github.com/libremesh/lime-packages/blob/master/packages/lime-proto-bgp/Makefile#L24
> with:
> `DEPENDS:=+bird1-ipv4 +bird1-ipv6 +lime-system +lua`

@a-gave your solution sounds like a great temporary fix. Can you prepare the pull request with this change? After this is updated the way you say, I would close this issue assuming that it's fixed.

**Comment by rallep71** [comment]
Hello everybody,

I've changed that for me now, it works. 

please fix it in the Master

**Comment by ilario** [comment]
@rallep71 do you mind doing a pull request with this change?

**Comment by rallep71** [comment]
Hello,
i don't really understand this question, i think that the developers of libremesh are reading this. 

i have made this change in my site and it works, i think it should be in the code . Reason, other people who compile the code don't have this error message in make anymore.

and honestly i don't know much about the pull requests here at github

**Comment by ilario** [comment]
> and honestly i don't know much about the pull requests here at github

If you want to try, here are some instructions (the easiest way I know), otherwise tell me and I'll do it, no problem at all :)

1) open the file you want to modify on Github: https://github.com/libremesh/lime-packages/blob/master/packages/lime-proto-bgp/Makefile#L24
2) click on the "Edit this file" button on the top right
3) do the edit
4) in the fields below, write a description for the commit (can be as easy as "lime-proto-bgp update dependencies")
5) click on "Commit changes"

**Comment by rallep71** [comment]
hello ilario,
thank you for your answer.
i would like to ask you to do it for me right now, i have to read up on the committing first, thank you

**Comment by ilario** [comment]
Done :D 
Check out #764, it will remove the warning for people compiling on 19.07 but it will add the warning for people still using 18.06.
