### ISSUE TITLE
Use pingcheck instead of watchping

### ISSUE THREAD

**Issue by p4u** [libremesh/lime-packages#66]
A new OpenWRT/LEDE package written in C has been released https://github.com/br101/pingcheck

It uses UBUS to communicate the current status and is compatible with UCI.

It seems a much better option than the current watchping used in LiMe for bmx6 auto gw mode and some other packages.

**Comment by FreifunkUFO** [comment]
pingchecks will have problems with captive-portal-splashed internet-gateways. So ping may see "internet", while access is still forbidden/splashed.

so for olsr-freifunk there is a very old package, which tries to get a http-website, also with treshold
https://github.com/openwrt/luci/tree/master/contrib/package/freifunk-gwcheck

**Comment by aparcar** [comment]
If pingcheck does [not support ipv6](https://github.com/br101/pingcheck/issues/1) and a http crawl as requested by @FreifunkUFO we may should simply extend watchping and close this issue?

**Comment by G10h4ck** [comment]
It seems a good starting point for a LiMe related GSoC proposal

**Comment by aparcar** [comment]
@G10h4ck so extend watchping or pingcheck?

**Comment by G10h4ck** [comment]
Evaluating which one is more adecuate can be part of the proposal, actually there was an idea about this last year

https://wiki.freifunk.net/Ideas_GSoC_2017#Improve_Easy_Internet_Sharing_in_LibreMesh

**Comment by br101** [comment]
pingcheck can use HTTP (option protocol tcp, default tcp port 80) to check connectivity. it just checks if the tcp connect on port 80 succeeds or not, and does not request a webpage, though...

**Comment by G10h4ck** [comment]
In that case it doesn't improve on the ICMP check, the problem with ICMP is that captive portals usually fake the ICMP answer so the checker thinks that there is internet when there is not, same happens with a simple connection on port 80...

One way to check this is doing like android phones does that checks for a specific google page that always return 200 OK

**Comment by tekoholic** [comment]
Any progress on this? I can't seem to get watchping to do it's job. Not sure that pingcheck would either, am going to test it in the coming few days. In the end, which one I will support will depend on which one actually does what it is supposed to do. Another option for consideration might be apinger, although it is limited to icmp so far as I have read, but at least does seem to have multi-interface options, among other things that watchping simply lacks...

**Comment by gmarcos87** [comment]
@tekoholic were you able to run any tests with conclusive results?

**Comment by ilario** [comment]
See related #93 and [my comment on that issue](https://github.com/libremesh/lime-packages/issues/93#issuecomment-538345915).

**Comment by ilario** [comment]
Is everyone ok with merging the discussion on #93? Feel free to re-open if you believe the two issues are different.
