### ISSUE TITLE
FBW: when creating a new network warn the client that has to connect to a new AP

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#660]
When creating a new network with FirstBootWizard, the AP name changes and if the user was connected via wireless will wait forever on a "Checking connection" page.

The situation:
I was connected with my laptop to a freshly flashed router, via wireless
I created a new network using the FBW

The problem:
the "Checking connection" page was making me wait forever

The solution:
I suppose that the only possible solution (I'm not sure...) is to include in the "Checking connection" page a message suggesting: "If you're connected via wireless, connect to the $new_essid_name access point"

**Comment by germanferrero** [comment]
This issue has been addressed some time ago.

![Screen Shot 2020-10-30 at 13 17 16](https://user-images.githubusercontent.com/7140856/97730215-58b9bb00-1ab2-11eb-8148-6a041eed6157.png)

Can we close this issue?

**Comment by ilario** [comment]
I checked, it's fixed. Thanks!
