### ISSUE TITLE
shared-state affected by httpclient issue

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#662]
Currently, when using OpenWrt 19.07, shared-state does not work at all.
This happens because the luci.httpclient library, and specifically its parse_url function, does not recognize IPv6 link-local addresses.
The issue has already been reported to the LuCI repository here: https://github.com/openwrt/luci/issues/3380

**Comment by ilario** [comment]
Issue was solved upstream (https://github.com/openwrt/luci/commit/1d2b4c777fd47f8d520b21d7085d3e7eb387cf02 and https://github.com/openwrt/luci/commit/af5d665a70371f73b63e77cdc7543520f5a1641e) and the fix included in the openwrt-19.07 branch.

**Comment by spiccinini** [comment]
Great!
