### ISSUE TITLE
Parse error in Pirania edit portal content

### ISSUE THREAD

**Issue by hiurequeiroz** [libremesh/lime-packages#693]
when I try to save the portal content on access page it fails returning this error: 
![Captura de tela de 2020-03-09 16-21-52](https://user-images.githubusercontent.com/6631731/76250973-02e38a80-6225-11ea-96a6-7eaad973d855.png)

**Comment by ilario** [comment]
I suppose this has been already fixed in the last 3 years. @hiurequeiroz please re-open if this still happens.
