### ISSUE TITLE
Pirania entry in looping error when acess in first time

### ISSUE THREAD

**Issue by hiurequeiroz** [libremesh/lime-packages#694]
Using firefox in an ubuntu operating system.
Pirania loops when you try to run the /www/cgi-bin/pirania/portal script and never loads the page.

Ps. in the cell phone we dont have this error

**Comment by G10h4ck** [comment]
Happening to me too Firefox on Gentoo, this branch on which @spiccinini is working seems have addressed that issue https://github.com/libremesh/lime-packages/tree/pirania_into_shape

**Comment by ilario** [comment]
I suppose this has been fixed in the last 3 years, closing. @spiccinini @G10h4ck please re-open if this still happens.
