### ISSUE TITLE
fix some luci problems due to updates

### ISSUE THREAD

**Issue by FreifunkUFO** [libremesh/lime-packages#73]
i tested luci-mod-status on our freifunk firmware (based on lede) and had to fix that to get graphs

https://github.com/freifunk-leipzig/lime-packages/pull/1/commits/3d8d4c86f35c09fceab771dcbeed557a69b0ed17

maybe some other luci pages also have problems

**Comment by FreifunkUFO** [comment]
so f.i. https://github.com/libremesh/lime-packages/pull/74

**Comment by p4u** [comment]
So the PR is merged. Thanks!

**Comment by FreifunkUFO** [comment]
I was expecting, that other luci-modules could also have problems.
So when closing the issue you were sure all luci is working properly? Otherwise please reopen ticket.

My PR was only for fixing luci-mod-status
