### ISSUE TITLE
Pirania clears iptables rules while reading db

### ISSUE THREAD

**Issue by luandro** [libremesh/lime-packages#732]
When the cronn to read the Pirania db runs, all devices are blocked by iptbales, until reading is done. Depending on the size the db this can take a long time. Which is terrible if you're streaming.

`captive-portal update` parece estar causando o problema
```
elif [ "$1" = "update" ] ; then
 clean_sets
 set_ipsets
 exit
```

não poderia ser esse clean_sets que esta dando problema?

o problema é que tarda como 5 segundos los scripts, e as vezes rodam multiplas vezes
me parece que `ipset -exist add pirania-auth-macs $mac` as vezes corre mas não faz nada
me parece que ao inves de usarmos clean_sets deveriámos ter uma função diff_sets

**Comment by spiccinini** [comment]
This problem may also be related to captive-portal update being called more than it should (only when it is needed).

**Comment by ilario** [comment]
Does this still happen or can we close this?

**Comment by luandro** [comment]
Fixed by https://github.com/libremesh/lime-packages/pull/893
