### ISSUE TITLE
SHA-512 bug

### ISSUE THREAD

**Issue by rallep71** [libremesh/lime-packages#751]
Hello,

I received the following message while compiling.

WARNING: Applying padding in /media/Data/Libremesh/openwrt/bin/packages/mipsel_24kc/packages/Packages to workaround usign SHA-512 bug!

end of make 

openwrt 19.07.3

**Comment by ilario** [comment]
Thanks for reporting, I never saw that message before.
I looked a bit on the internet and it is a harmless warning implemented by OpenWrt people. Don't worry about it, it's just technical stuff that do not affect us at all.

The explanation of what that means is in this comment on this commit:
https://git.openwrt.org/?p=openwrt/openwrt.git;a=commitdiff;h=e1f588e446c7ceb696b644b37aeab9b3476e2a57

I'm going to close the issue, feel free to open it again if you think that some accident is related to this warning.
