### ISSUE TITLE
search for a possebillaty to sysupgrade (-n) keep-settings-light  just with lime_node

### ISSUE THREAD

**Issue by der-nele** [libremesh/lime-packages#769]
for keep config clean
thanks.
and the keep the ssh-key would be nice too. but no other settings at all. 
my reason for this is, that i try to admin a mesh with 17 nodes and my most important settings are the node-name, ap ssid and the cannels. and if i make keep settings, the routers make strange things (for exapel do not schow the libremesh logo in the terminal)
and if i make sysupgade -n /tmp then the logo is there but i have to update and rename every router and have a very hard work to make a plan to do not lose the connections. there are more reasons for me but the list is to long and my english to bad.

**Comment by ilario** [comment]
Check out the `lime-sysupgrade` command from lime-system package:
https://github.com/libremesh/lime-packages/blob/fa4fd5f8d3f78ace52a52b53bea87e06a3ed7827/packages/lime-system/files/usr/bin/lime-sysupgrade#L19-L22

it should do exactly what you ask for (but I never used it).
The files which will be preserved, by default are these ones:
https://github.com/libremesh/lime-packages/blob/187deb71f14c34bf3d351256865df09890e20406/packages/lime-system/files/etc/config/lime-defaults#L11

and these ones:

https://github.com/libremesh/lime-packages/blob/c4fb7118e8393b65264626cb60340f0bb0228793/packages/lime-system/files/lib/upgrade/keep.d/libremesh#L1-L3

So for having the private SSH key preserved you will have to have something like:
```
config lime system
	option keep_on_upgrade 'libremesh /etc/sysupgrade.conf /etc/dropbear/dropbear_rsa_host_key'
```
in /etc/config/lime-community (or in lime-node).

To keep the SSH key makes a lot of sense, I'll prepare a pull request with that.

I'll close the issue as I think that lime-sysupgrade is what you were looking for, but feel free to re-open it if there is more!

**Comment by ilario** [comment]
Sorry, I just edited my previous comment as I got the wrong version of the lime-defaults. The SSH keys are already being preserved by default by lime-sysupgrade.

**Comment by ilario** [comment]
I tested the lime-sysupgrade on a TP-Link WDR3600 and do not preserve the configuration as it should.
Seems that in the current state it can work only with the LibreRouter.
I am preparing a pull request to fix it.

**Comment by spiccinini** [comment]
Ilario,.the keep on upgrade list must contain filelists and not files itself, or at least that was the design decision made by pau as far as I understand

**Comment by spiccinini** [comment]
Disregard my last comment, I read your response in my email and didn't  understand it correctly.

**Comment by ilario** [comment]
Oky :)
Check out #772

**Comment by spiccinini** [comment]
Great! Thanks Ilario!

**Comment by der-nele** [comment]
thanks for that. so my computer skills are small so i ride this and than i do just keep the lime node root@node1: lime-sysupgrade /tmp/libremeshTEST.bin [lime-node]?

**Comment by ilario** [comment]
Sorry for that but lime-sysupgrade currently does not work.
We are fixing it on #772

**Comment by ilario** [comment]
@der-nele the lime-sysupgrade has been fixed in the LibreMesh master branch.
This means that you'll need to update the feeds of your compilation directory (or to start a new compilation from scratch), flash the new image to your routers with the normal `sysupgrade -n /tmp/openwrt...sysupgrade.bin` and from there on you will have available the `lime-sysupgrade /tmp/openwrt...sysupgrade.bin` command.
Please confirm if it correctly solves your issue!
