### ISSUE TITLE
Conventional design of branch naming

### ISSUE THREAD

**Issue by FreifunkUFO** [libremesh/lime-packages#796]
Lets rename the branches to the openwrt standard used names. 
there is no need for different treatment of lime-packages, it would confuse many people.

the standard is: master-branch is for development, all openwrt releases have own branches

**Comment by FreifunkUFO** [comment]
example: stuff for openwrt 19.07 is named like this:
https://github.com/freifunk/openwrt-packages/tree/openwrt-19.07
https://github.com/openwrt-routing/packages/tree/openwrt-19.07
https://github.com/openwrt/packages/tree/openwrt-19.07
https://github.com/openwrt/luci/tree/openwrt-19.07
![name-the-brunch](https://user-images.githubusercontent.com/2579265/98226859-e3893280-1f56-11eb-9e2b-2e83deb33f54.png)

ping @spiccinini 
https://github.com/libremesh/lime-packages/issues/749

**Comment by ilario** [comment]
+1

**Comment by spiccinini** [comment]
Curently we are targeting 18.06 and 19.07 and maybe master with the same codebase. 
After the release we would be targeting 19.07 and 20.xx (if openwrt does a release this year) and  master. 
Having one branch per openwrt target would be a lot of work to maintain. I still think that we can achieve compatibility with multiple openwrt versions with the same codebase in an easier way than having  one branch per openwrt version, or at least that is my opinion of the last two years experience.

**Comment by ilario** [comment]
@FreifunkUFO can you please check the proposal of naming that is here?
https://github.com/libremesh/lime-packages/issues/951#issuecomment-1431132608

**Comment by ilario** [comment]
No updates. So I suppose this is solved enough...?
