### ISSUE TITLE
ubus-lime-metric uses /cgi-bin/hostname which belongs to FBW but does not depend from FBW

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#803]
ubus-lime-metric is looking for /cgi-bin/hostname on the other nodes:

https://github.com/libremesh/lime-packages/blob/3883b01915b4e646d685812736c4e425b4ef1d21/packages/ubus-lime-metrics/files/usr/sbin/last_internet#L17

https://github.com/libremesh/lime-packages/blob/3883b01915b4e646d685812736c4e425b4ef1d21/packages/ubus-lime-metrics/files/usr/sbin/last_internet#L28

but this file is not provided in ubus-lime-metric, instead it is provided by first-boot-wizard which is not a dependency of ubus-lime-metric, and it should not be.

ubus-lime-metric should also provide a /cgi-bin/hostname equivalent file. In order to avoid file conflicts that file can be generated with uci-defaults or simply have another name (I prefer the second option).

**Comment by ilario** [comment]
And ubus-lime-metric should depend on uhttpd.

**Comment by ilario** [comment]
@spiccinini opinions?
Adding a /www/cgi-bin/ubus-lime-metric-hostname to ubus-lime-metric package?

**Comment by ilario** [comment]
I'm not sure it's a release blocker but for sure this will break ubus-lime-metrics with the current compilation instructions (not including FirstBootWizard).

**Comment by spiccinini** [comment]
Thanks Ilario for clarifying this issue.

**Comment by spiccinini** [comment]
I am proposing in #815 to move the cgi-bin/hostname into ubus-lime-utils and then make first-boot-wizard and ubus-lime-metrics depend on it.

**Comment by ilario** [comment]
Great solution! It makes a lot of sense in my opinion, thanks @spiccinini!
