### ISSUE TITLE
FBW: 403 error when fetching lime-community

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#807]
Originally, the `/etc/config/lime-community` file has `-rw-r--r--` permissions.
When creating a new network, the `/etc/config/lime-community` file has read permissions only for root: `-rw-------`.
This causes the failure in wget (403: Forbidden) on the other nodes when trying to download the lime-community file.

Before creating a new network:

```
# ls -l /etc/config/lime*
-rw-r--r--    1 root     root           196 Sep  6 16:19 /etc/config/lime-app
-rw-------    1 root     root          2300 Nov 10 12:19 /etc/config/lime-autogen
-rw-r--r--    1 root     root           209 Sep  6 16:19 /etc/config/lime-community
-rw-r--r--    1 root     root          2377 Sep  6 16:19 /etc/config/lime-defaults
-rw-r--r--    1 root     root           374 Nov 10 12:19 /etc/config/lime-node
```

after creating a new network using FirstBootWizard:

```
# ls -l /etc/config/lime*
-rw-r--r--    1 root     root           196 Sep  6 16:19 /etc/config/lime-app
-rw-------    1 root     root          2199 Nov 10 13:08 /etc/config/lime-autogen
-rw-------    1 root     root           237 Nov 10 13:08 /etc/config/lime-community
-rw-r--r--    1 root     root          2377 Sep  6 16:19 /etc/config/lime-defaults
-rw-------    1 root     root           134 Nov 10 13:08 /etc/config/lime-node
```

I am testing on top of OpenWrt 19.07.4

**Comment by spiccinini** [comment]
Oh this is a really nasty bug....I don't understand how as umask by default is 0022 ...

**Comment by spiccinini** [comment]
I am not able to reproduce it :( What is the output of `umask` in both routers?

**Comment by ilario** [comment]
`umask` is 0022 on both routers.
What changes the permissions is `uci commit`.
Try with
```
ls -l /etc/config/lime-node
uci set lime-node.wifi.ap_name="ciao11"
uci commit
ls -l /etc/config/lime-node
```

Doesn't it happen for you?

**Comment by spiccinini** [comment]
I was able to reproduce it. Somehow the default write permissions of uci changed in 19.07.
