### ISSUE TITLE
Build only libremesh packages in CI

### ISSUE THREAD

**Issue by spiccinini** [libremesh/lime-packages#819]
Is there a reason why CI build all the packages instead to build only libremesh packages?
Currently tt takes 1 hour when it should only take a couple of seconds.

**Comment by ilario** [comment]
I suppose it cannot build just the packages fue to an OpenWrt buildroot limitation?
To compile the whole image could be used for providing some binary image, but I have no idea if the Github actions would be happy to compile the whole ath79 target.

**Comment by aparcar** [comment]
If you depend on packages they are compiled first, I think that's a limitation of the current SDK.

**Comment by spiccinini** [comment]
Thanks for the clarification, closing the issue as this should have to be solved upstream.
