### ISSUE TITLE
Internet failover for every router

### ISSUE THREAD

**Issue by amuuza** [libremesh/lime-packages#822]
There are Router A, B and C with LiMe based on OpenWRT 19.07 (the tests have been done with BMX6 and Babel, getting the same results). They are connected as shown below:

```
 ISP-A                     ISP-C
   |                         |
RouterA <--> RouterB <--> RouterC
```
RouterA WAN port is connected to ISP-A to reach the Internet.
RouterC WAN port is connected to ISP-C to reach the Internet.

Router B can reach the Internet via both ISP-A and ISP-C without a
problem.

Let's consider RouterB is reaching now the Internet through ISP-A.

If ISP-A loses Internet connectivity, Router B will switch its Internet gateway automatically to ISP-C (it may take several minutes though, maybe something around 10, I'm not sure).

However, despite having ISP-A without Internet, RouterA will never switch to ISP-C automatically. It will need a manual reboot to do the switch. 

It would be nice to have RouterA doing the Internet failover too, while also checking Internet availability from its own WAN interface to be restored when it's back.

**Comment by ilario** [comment]
More info on the "Internet failover" thread in lime-users archives of [November](https://lists.libremesh.org/pipermail/lime-users/2020-November/thread.html) and [December](https://lists.libremesh.org/pipermail/lime-users/2020-December/thread.html).
And closely related to #93, especially on this: https://github.com/libremesh/lime-packages/issues/93#issuecomment-739014966 and [this](https://lists.libremesh.org/pipermail/lime-users/2020-December/001858.html) where a solution based on metrics is hypothesized.
