### ISSUE TITLE
lime-app fetching name

### ISSUE THREAD

**Issue by rallep71** [libremesh/lime-packages#850]
hello @all,

ive following issue in lime app---fetching name,,,,search search search, openwrt 19.07.7, i have given each router its own name in lime-node so that i can distinguish them better. but the status fetching name does not change, see pictures, no matter on which router, this is an example of router "rootnode"
![fetchingname](https://user-images.githubusercontent.com/2786491/109421515-f4fbbc00-79d7-11eb-8de4-a0e7f31a7f5d.png)
![fetchingname1](https://user-images.githubusercontent.com/2786491/109421519-f88f4300-79d7-11eb-8e33-507561d8961d.png)
when i open the page for the first time it remains empty, this is another node in the same mesh
![fetchname3](https://user-images.githubusercontent.com/2786491/109427521-0acaaa80-79f3-11eb-8993-df53bc2180b8.png)

**Comment by ilario** [comment]
@germanferrero @nicopace @gmarcos87

**Comment by spiccinini** [comment]
Thanks @rallep71 for the report! I've fixed it in #851
