### ISSUE TITLE
daemon.err babeld Late hello: bufferbloated neighbor 

### ISSUE THREAD

**Issue by rallep71** [libremesh/lime-packages#861]
Hello, i see this in my logfile, what ist this?

 daemon.err babeld[1443]: Late hello: bufferbloated neighbor fe80::b24e:26ff:fe45:63abr

System: Asus RT AC51U, Opebnwrt 19.0.7.7, Libremesh Git Master.

Thx

**Comment by spiccinini** [comment]
Hi! I don't know, never seen it!

**Comment by ilario** [comment]
2 years without any other report nor investigation. Closing. Feel free to re-open if you have more info.
