### ISSUE TITLE
lime.network: mesh_ifaces to return up&running ifaces 

### ISSUE THREAD

**Issue by germanferrero** [libremesh/lime-packages#866]
Currently it retrieves mesh and adhoc interface names from the uci-config. But, in some cases this interfaces cannot be setup and it is not available, let's say the case in which the radio hardware is missing. Currently if this is the case the LimeApp will show the interface in the align page without handling it correctly (i.e, it stucks in a loading message state).
I think that returning only mesh and adhoc interfaces which are under `/sys/class/net/` would be more useful, for this and other use cases.

**Comment by ilario** [comment]
Where should be done, this change?
In this file? https://github.com/libremesh/lime-packages/blob/master/packages/lime-system/files/usr/lib/lua/lime/network.lua

**Comment by ilario** [comment]
Can anyone confirm this is a real problem?
Can the hardware be different from what OpenWrt thinks?
In this case, is it going to appear in /etc/config/network?

**Comment by ilario** [comment]
As @germanferrero is not actively developing for LibreMesh right now, @spiccinini do you think you can manage this?

**Comment by ilario** [comment]
Wooosh dead issue since 2021 is going to be closed.
