### ISSUE TITLE
OPKG does not find our Packages.gz for releases

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#888]
Just tested an image downloaded from 
http://repo.libremesh.org/expansive_emancipation/2020.1/targets/ath79/generic/

```
# opkg update
[...]
Downloading http://feed.libremesh.org/2020.1/Packages.gz
*** Failed to download the package list from http://feed.libremesh.org/2020.1/Packages.gz

Downloading http://feed.libremesh.org/profiles/Packages.gz
Updated list of available packages in /var/opkg-lists/profiles
Downloading http://feed.libremesh.org/profiles/Packages.sig
Signature check passed.
Collected errors:
 * opkg_download: Failed to download http://feed.libremesh.org/2020.1/Packages.gz, wget returned 8.
```

OPKG looks for `.../2020.1/...` but, as the directory in the feed is `v2020.1`: https://github.com/libremesh/lime-feed/tree/gh-pages/v2020.1, it should look for `.../v2020.1/...` instead.

I suppose that the fix is as easy as add a `v` here (?):

https://github.com/libremesh/lime-packages/blob/06399e5de7fb7b9d3cf13c19f7bf70accb11299a/packages/lime-system/files/etc/uci-defaults/92_add-lime-repos#L18

**Comment by RhnSharma** [comment]
I would like to take this one.

**Comment by ilario** [comment]
Dear @RhnSharma, sorry for the long delay and thanks for the good pull request!
As commented by @spiccinini in https://github.com/libremesh/lime-packages/pull/889#issuecomment-879440213 an alternative solution would be to remove the `v` from the tag name before uploading the compiled packages.
Would you mind to prepare an alternative pull request with that other change instead?
I think that it would be enough to replace this:
https://github.com/libremesh/lime-packages/blob/c2f7261c8cca7de907363aea2bee69e930b45dcb/.github/workflows/build.yml#L29

with this:
`export TAG=$(echo "${{ github.ref }}" | cut -d '/' -f 3- | tail -c +2)`

where the tail command will remove the first character of the string (which is the `v`).
Thanks!!!
