### ISSUE TITLE
Remind users in ssh sessions that safe-reboot is counting

### ISSUE THREAD

**Issue by germanferrero** [libremesh/lime-packages#894]
It's pretty common for many of us, that during an ssh session we execute safe-reboot in order to safely apply changes. And then we forget to execute safe-reboot cancel in the right moment.

Can we find a way to show up in the terminal, a periodic or constant reminder that safe-reboot is "active". Ideas?

**Comment by ilario** [comment]
Adding something in $PS1 shell prompt?

**Comment by germanferrero** [comment]
I love the idea!

**Comment by ilario** [comment]
I just remembered I proposed this in 2017 but @stalebot closed the issue: #238.

**Comment by ilario** [comment]
The original report in #238 has more information. Re-opening that one and closing this duplicate.
