### ISSUE TITLE
Only the current node position can be seen in the map, no other nodes can be seen

### ISSUE THREAD

**Issue by ggsnpdsn** [libremesh/lime-packages#895]
Is the topology displayed in the map not supported?

**Comment by germanferrero** [comment]
Hi @ggsnpdsn, if we are talking about LimeApp's Map screen, yes it does!
Map coordinates for each node are distributed in the mesh via SharedState, the distributed database system.
Once the data is there, you should be able to click on "view community" and all the mesh nodes with configured map coordinates should be displayed.
If it doesn't can you provide a more detailed explanation of your issue?

**Comment by ilario** [comment]
Sadly, only the selection of both Babeld and Batman-adv is currently supported.
It would be great to support also other options, but for now I would close this as it has been observed in a likely-nonfunctional environment.

**Comment by ilario** [comment]
Please reopen if you observe this also with Babeld+Batman-adv or if "Batman-adv only" is reasonably close to be usable.
