### ISSUE TITLE
Add AP WPA2 and Country Code support in lime-webui

### ISSUE THREAD

**Issue by p4u** [libremesh/lime-packages#90]
The [AP WPA2](/libremesh/lime-packages/blob/develop/packages/lime-docs/files/lime-example#L66) and the [Country Code](/libremesh/lime-packages/blob/develop/packages/lime-docs/files/lime-example#L55) options are already supported on [config/lime](/libremesh/lime-packages/blob/develop/packages/lime-system/files/etc/config/lime). The Simple Config module of [lime-webui](/libremesh/lime-packages/tree/develop/packages/lime-webui) must support the configuration of those. The encryption type should be "psk2" by default, not configurable by the end-user.

**Comment by ilario** [comment]
Merged with the more general #327, closing.
