### ISSUE TITLE
Safe Reboot Web Interface

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#91]

**Comment by ilario** [comment]
A bit of description please, what is this issue about?

**Comment by nicopace** [comment]
Sure.
Some time ago @altergui developed a functionality called 'safe-reboot'.
The idea is to add a luci module that allows GUI users to use this functionality.
The way we thought about this was to add a button next to 'save and apply' like 'save and test' that would restart the router and apply this configs... but if the user does not go inside the router and says 'this config is valid' the router would restart itself after some time with the previous config applied and the new config pending as it were before.

**Comment by ilario** [comment]
Ok, thanks.
Is this thing already implemented in LEDE?
If it's not, shouldn't we push things there?

---

> @altergui developed [...] GUI users
LOL

**Comment by nicopace** [comment]
I don't really know what it takes to make this things implemented in LEDE... the luci module depends on safe-reboot... if safe-reboot is already on LEDE then having this on LEDE would be the way to go.

**Comment by ilario** [comment]
web ui stuff... tagging @gmarcos87

**Comment by gmarcos87** [comment]
Ok, related pull-request open in #477

**Comment by nicopace** [comment]
This issue is outdated as we are not using luci anymore and this was thought from a luci perspective.
