### ISSUE TITLE
Circular dependency: pirania and shared-state-pirania

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#942]
The circular dependency problem is based:

* `shared-state-pirania` imports `voucher` (from `pirania` package, this dependency is being added to the Makefile in #941)
* `pirania` imports `shared-state` (and uses it in a way that I don't understand if justifies the need for `shared-state-pirania`) but depends on `shared-state-pirania` in its Makefile

`pirania` uses `shared-state` here:
https://github.com/libremesh/lime-packages/blob/99c38175e54245b144e7abab8b7f43b31475ed8f/packages/pirania/files/usr/lib/lua/portal/portal.lua#L35
and here:
https://github.com/libremesh/lime-packages/blob/99c38175e54245b144e7abab8b7f43b31475ed8f/packages/pirania/files/usr/lib/lua/portal/portal.lua#L46

Does this require `shared-state-pirania` or `shared-state` is enough?

If it actually require `shared-state-pirania`, the solution would be to merge `pirania` and `shared-state-pirania`.

**Comment by a-gave** [comment]
Fixed on Mar 19, 2024 by https://github.com/libremesh/lime-packages/pull/1097 in commit https://github.com/libremesh/lime-packages/pull/1097/commits/12a078d0f9699479b7c12367a12e1777c8205781
