### ISSUE TITLE
Error in first run of migrate-wifi-bands-cfg

### ISSUE THREAD

**Issue by ilario** [libremesh/lime-packages#945]
When installing lime-system via `opkg` on a clean OpenWrt system, this error is printed:

```
Configuring lime-system.
/usr/bin/lua: /usr/bin/migrate-wifi-bands-cfg:38: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
	[C]: in function 'pairs'
	/usr/bin/migrate-wifi-bands-cfg:38: in function 'move_restof_to_specific_band'
	/usr/bin/migrate-wifi-bands-cfg:51: in function 'migrate_file'
	/usr/bin/migrate-wifi-bands-cfg:59: in main chunk
	[C]: ?
```

this happens as at the first install there is no `lime-community` nor `lime-node` files and this list is empty:

https://github.com/libremesh/lime-packages/blob/de7f38f6e555a18684728fd4c02ec866e3abc753/packages/lime-system/files/usr/bin/migrate-wifi-bands-cfg#L7

So there should a check for the `options` variable to not be `nil` between these lines:

https://github.com/libremesh/lime-packages/blob/de7f38f6e555a18684728fd4c02ec866e3abc753/packages/lime-system/files/usr/bin/migrate-wifi-bands-cfg#L37-L38

**Comment by germanferrero** [comment]
I'll be out of keyboard for a while, if someone else can take this, go
ahead :)
