### ISSUE TITLE
Review IPv6 autogw mode

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#96]

**Comment by p4u** [comment]
More info here: https://github.com/libremesh/lime-packages/pull/71

Added @dangowrt as assignee, cause he sent the first push request.

**Comment by dangowrt** [comment]
I was played a lot with isc-dhcp lately and hence had a deeper look at how dynamically assigned IPv6 addresses and prefixes are being propageted and delegated using ubus. Imho this be implemented in such way that a change in the assigned IPv6 address/prefix from upstream (ie. xDSL or Cable ISP) will trigger a notification to change the announced gateway prefix in bmx6. I can take care of that.
However, what is still missing is the functionality on the client side which requiress bmx6 to dynimically assign the current prefix belonging to a gateway to its tunIn interface.

**Comment by p4u** [comment]
> However, what is still missing is the functionality on the client side which requiress bmx6 to dynimically assign the current prefix belonging to a gateway to its tunIn interface.

Then would be nice to see if @axn has the time to implement this on bmx6.

**Comment by G10h4ck** [comment]
We talked about this in Athens and we decided this will not be included in for this release
