### ISSUE TITLE
Bundle Lime Workarounds

### ISSUE THREAD

**Issue by nicopace** [libremesh/lime-packages#97]
During the development of LibreMesh we found several way to deal with upstream inconcistencies or hardware failures. These ones we called them worarounds.
Get all of them together into a package to easen its maintenaince.

**Comment by G10h4ck** [comment]
Hardware specific quircs are supposed to be handled with hardware detection plugins

**Comment by ilario** [comment]
Are the workarounds these ones?
https://github.com/libremesh/network-profiles/tree/master/quintanalibre.org.ar/comun/etc/uci-defaults

**Comment by nicopace** [comment]
@nicoechaniz ?

**Comment by nicopace** [comment]
I guess so... but let's hope others can comment

**Comment by ilario** [comment]
Related discussion is going on in #137

**Comment by ilario** [comment]
smonit was merged in #142, some of the workarounds got implemented in it.

**Comment by nicopace** [comment]
@ilario are you sure all the workoarounds already in smonit? @G10h4ck @p4u @altergui can you confirm?

**Comment by ilario** [comment]
@nicopace no I'm not

**Comment by nicopace** [comment]
Then let's the guys close the issue :)
