### ISSUE TITLE
Fix category for shared-state-network_nodes

### ISSUE THREAD

**Issue by aparcar** [libremesh/lime-packages#995]
It's hidden in an entirely different category than all other shared-state plugins

https://github.com/libremesh/lime-packages/blob/73e92cbb63e8d9ecb6660015e86b709b4b0ecacd/packages/shared-state-network_nodes/Makefile#L11

**Comment by a-gave** [comment]
This was fixed on Jul 28, 2023 by commit https://github.com/libremesh/lime-packages/commit/ffb9ee13532e82e5b587cb0806add79059e7a2cd
